version: '3'
services:
  {{user}}_es8:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3

    container_name: {{user}}_es8
    environment:
      - cluster.name={{user}}-es8-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data8-{{user}}:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:{{port}}:9200"
    networks:
      - elastic_{{user}}_es8

  {{user}}-eshq8:
    restart: always
    image: elastichq/elasticsearch-hq
    container_name: {{user}}-eshq-8
    networks:
      - elastic_{{user}}_es8
    ports:
      - "127.0.0.1:{{es8hq_port}}:5000"

volumes:
  data8-{{user}}:
    driver: local

networks:
  elastic_{{user}}_es8:
    driver: bridge

